### ISSUE TITLE
Server Crashes Upon Using Magic Gems

### ISSUE THREAD

**Issue by someeodtech** [ACEmulator/ACE#1299] opened 2019-01-16 23:05 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.

Upon "using" a treasure generated Black Garnet with spells on it, the server unexpectedly crashes before giving stack traces 

### The log given by the failure.

None captured

### Desired functionality.

No crashes

**Comment by gmriggs** [comment] 2019-01-16 23:07
Duplicate of https://github.com/ACEmulator/ACE/issues/1296

**Closed by gmriggs** 2019-01-16 23:07 UTC
